### ISSUE TITLE
Ethnographic Layers

### ISSUE THREAD

**Issue by wboykinm** [GeoSprocket/btv-geographic#18]
Needs more specificity - something to [this effect](https://a.tiles.mapbox.com/v3/landplanner.i7e0ojd7/page.html?secure=1#12/44.4965/-73.2053) may be what's intended, but it's not a simple addition to the list.

Also note that basic racial count numbers from 2010 are [already present in the attributes of the census block dataset]() - they are available for investigation in a GIS context.

![2014-05-11_2318](https://cloud.githubusercontent.com/assets/735463/2940508/3b52343c-d984-11e3-9300-8e6850f77b56.png)

**Comment by wboykinm** [comment]
@sebeckett I fear this is out of scope for this upgrade. I'm running low on available hours.

**Comment by sebeckett** [comment]
The tiles you linked to aren't displaying for me, but that's ok. This isn't a top priority for this upgrade.
Thanks @wboykinm

**Comment by wboykinm** [comment]
Ah yeah - that's an old tileset I cleared out to make space.
