### ISSUE TITLE
Historical Maps

### ISSUE THREAD

**Issue by wboykinm** [GeoSprocket/btv-geographic#20]
Get URLs from Sean

**Comment by sebeckett** [comment]
Bill-
Here's a trial of the first georef'ed historical map. Would you please throw these tiles in as a new layer and see if all displays correctly:

http://mapwarper.net/layers/tile/572/{z}/{x}/{y}.png

**Comment by wboykinm** [comment]
@sebeckett That's great - will try it out in a demo. Thanks!

**Comment by wboykinm** [comment]
@sebeckett Yep - works perfectly: http://bl.ocks.org/wboykinm/fe3f3dd4cd9e9ccf275faf92a6eafe12

Those old sanborns are in the mental grid of an engineer - you might need to go crazy on the control points and even use the spline method to lock them to the current street grid.

**Comment by sebeckett** [comment]
great! Thanks for the tip on the spline.
I know this is just a tester demo, but just in case I wasn't clear (happens a lot), i'm envisioning an on/off layer (potentially with transparency slider?) rather than a swipe. Either way, i'll chip away at some other maps over the next month and get back to you!

**Comment by wboykinm** [comment]
@sebeckett no, you were totally clear - I was just using the swipe as an example.

**Comment by wboykinm** [comment]
New layers added by @sebeckett:

http://mapwarper.net/layers/572

http://mapwarper.net/layers/576

http://mapwarper.net/layers/586

**Comment by wboykinm** [comment]
@sebeckett These are now all incorporated (and **fascinating**) - did you want to add any others? Note that any changes you make in mapwarper to the maps above will make it into the app.

**Comment by sebeckett** [comment]
@wboykinm I think this is about all I'll have time to collage and georeference for this project.
Wondering whether transparency sliders for these would be a can of worms outside of our budget.
Thanks!

**Comment by wboykinm** [comment]
@sebeckett I'm afraid transparency is a bit more than I have time for this round.
