### ISSUE TITLE
Fit in all the new stuff

### ISSUE THREAD

**Issue by wboykinm** [GeoSprocket/btv-geographic#24]
With an [accordion](https://davidwalsh.name/download-attribute), which will require a slight refactor to the `addLayer()` function.

**Comment by sebeckett** [comment]
Is there a way for me to preview the map so far?

**Comment by wboykinm** [comment]
@sebeckett Not at the moment since I'm working on a branch. But when I get these basics working I'll publish it. You **can** check it out yourself if you 
1. git clone the repository (the [windows github app](https://desktop.github.com/) is probably the fastest way to do this)
2. start a [local http server](http://stackoverflow.com/questions/17351016/set-up-python-simplehttpserver-on-windows)
3. check it out in your web browser (probably this address: `http://localhost:8000`)

**Comment by wboykinm** [comment]
I'll try to merge the branch this weekend. I usually work this way to avoid consigning the working version to the change history until I'm sure I have a working replacement (which I don't right now - still debugging 😀 )

**Comment by wboykinm** [comment]
All set here.
